tasks:
  - name: terraform
    before: |
      source ./bin/add_tf_aliases.sh
      source ./bin/install_terraform_cli.sh
      source ./bin/generate_terraform_api_login.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/add_tf_aliases.sh
      source ./bin/install_aws_cli.sh
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform